const express = require("express");
const cors = require("cors");
const dotenv = require("dotenv");
const authRoutes = require("./routes/auth");
const projectRoutes = require("./routes/projects");
const path = require("path");
// const attendanceRoutes = require("./routes/attendance");
dotenv.config();
const app = express();
app.use(express.static(path.join(__dirname, "../frontend")));
app.use(cors());
app.use(express.json()); 
app.use("/api/auth", authRoutes);
app.use("/api/projects", projectRoutes);
// app.use("/api/attendance", attendanceRoutes);
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server running on http://localhost:${PORT}`));